spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.1.7
    port: 5672
    username: guest
    password: guest    
  redis:
    host: 192.168.1.7
    port: 6379    
  sleuth:
    feign:
      enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://192.168.1.7:9411/
    sender:
      type: web
env: test3
girl:
  name: lili
  age: 25
